### ISSUE TITLE
Sh2-119 Coordinates incorrect

### ISSUE THREAD

**Issue by brickbots** [brickbots/PiFinder#227]
This seems like it may be an issue with more than one of the Sh2 catalog entries.  Probably needs a re-process/audit

**Comment by mrosseel** [comment]
might be something in the B1950 to J2000 conversion?
I've found the J2000 coordinates on heasarc, which match the wikipedia coordinates (on SH2-1) so that seems consistant. 
So either we fix the transformation - which is most interesting because we might need to do that again in the future - or we use the new coordinates from heasarc to at least fix the issue

**Comment by mrosseel** [comment]
[heasarc_sharpless.txt](https://github.com/user-attachments/files/16905007/heasarc_sharpless.txt)

**Comment by brickbots** [comment]
Fixed with #230
